remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
markdown_extensions:
  - attr_list
title: Henry Varley's Portfolio!
description: Welcome to the portfolio page showcasing Henry Varley's games!
header_pages:
- aboutme.md
footer_message: "Contact me at henryvarley14+contact@gmail.com"
