remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
markdown_extensions:
  - attr_list
title: Henry Varley's Portfolio!
description: Welcome to the portfolio page showcasing Henry Varley's games!
header_pages:
- aboutme.md
footer_message: "All above games are made by Henry Varley, however most art is not, and should be accredited on the itch.io page for the relevant game"
author_email: "henryvarley14+contact@gmail.com"
